### ISSUE TITLE
Fail to spoof canvas fingerprinting properly

### ISSUE THREAD

**Issue by ReporterX** [jake-cryptic/AbsoluteDoubleTrace#11]
Using 2.2.6
Firefox 66.0.3

Go to https://canvasblocker.kkapsner.de/test/test.html
Only the first test passes. The rest has a constant hash ID.

Those are enabled with default settings: 

Canvas Fingerprint Protection
Audio Fingerprint Protection
WebRTC Protection
Ping Protection
Screen Resolution Tracking Protection
Hardware Fingerprint Protection
WebGL Fingerprinting Protection (Beta)
Network Information Spoofer

**Comment by jake-cryptic** [comment]
Hi,

I'll have to look into this as the protection seems to work on: https://browserleaks.com/canvas

Unfortunately I can't tell you when this will be resolved as I'm very busy at the moment with exams, but I'll make sure that as soon as I can a fix will be pushed out.

Thanks

**Comment by jake-cryptic** [comment]
Hi, I had a few spare minutes to investigate and have created a fix for the issue, it will be rolled out in the next version of Trace. I'll close this issue once the update is pushed (I can't give an ETA right now)

**Comment by jake-cryptic** [comment]
After extensive testing of this issue, I have bad news. The issue cannot be fixed fully because of how the browser behaves. The reason for this is explained below:

When a page loads, Trace runs a script, the script loads the settings from storage and then checks what protections can run, it will then apply the protections. In most cases this is fine. However in this specific case of canvas fingerprinting, the tracking code is able to load before Trace can apply the protections...

There isn't much of a way around this, I have been trying to figure one out but came across this thread which basically said that it can't be done... https://bugs.chromium.org/p/chromium/issues/detail?id=54257

Luckily though, this issue seems to be very rare in the wild, as most tracking code must be loaded from a 3rd party server, or is loaded after the initial page load in which case Trace has had time to apply protections to the browser window... I will update this issue if I find a fix however it doesn't look likely.
