### ISSUE TITLE
Version: 2.3.0 - E-Tag Tracking Protection not working

### ISSUE THREAD

**Issue by gameb0y** [jake-cryptic/AbsoluteDoubleTrace#15]
I updated version 2.3.0, but E-Tag Tracking Protection not working anymore.

W7 x64
Tested:  Chrome Version 74, 75

**Comment by jake-cryptic** [comment]
Due to how Chrome handles headers, E-Tag protection cannot work correctly... I am considering removing it from Chrome due to this.

https://developer.chrome.com/extensions/webRequest#life_cycle_footnote

Extensions are now allowed to access: 
If-Modified-Since
If-None-Match
If-Range

Which are the headers needed to properly protect against E-Tag tracking

**Comment by jake-cryptic** [comment]
I just pushed Trace 2.3.5 which should restore the functionality of E-Tag protection to how it was before 2.2.6
