### ISSUE TITLE
Request: CSS Exfil Protection

### ISSUE THREAD

**Issue by gameb0y** [jake-cryptic/AbsoluteDoubleTrace#17]
The CSS Exfil vulnerability detailed in this lengthy post is a method attackers can use to steal data from web pages using Cascading Style Sheets (CSS). CSS - one of the building blocks of the modern web - is used by developers to control the look-and-feel of a website and is present on nearly every modern page on the internet. By crafting targeted CSS selectors and injecting them into a web page, an attacker can trick the page into sending pieces of data to a remote server (e.g. usernames, passwords, and sensitive data such as date of birth, social security numbers, and credit card numbers).

https://www.mike-gualtieri.com/css-exfil-vulnerability-tester

**Comment by jake-cryptic** [comment]
Hi,

I'm aware of this issue and have looked into it in the past.
The main issue is that this problem cannot easily be solved using a web extension. The extension you link to attempts to fix the issue by parsing each CSS rule itself rather than letting the browser do it, this can cause page loading issues from what I have read and there doesn't really seem to be a better way to fix it.

I'm not completely ruling out an implementation however it won't be worked on any time soon as there are other tracking methods that still need to be protected against that are more widely used.
